### PR TITLE
Ignore updates to source files while live-reloading is in progress #155

### LINKED ISSUE #155: Ignore updates to source files while live-reloading is in progress
Current: if source files are updated while a live-reload is in progress, there is high chance that the live-reload will crash out. IDEs do auto-saves of files at unpredictable times, which makes this problem particularly bad.

Suggested: Either queue (or at least ignore) any trigger to live-reload while there is an active live-reload.

### PR DESCRIPTION
**Pull request by rachx**
Resolves https://github.com/MarkBind/markbind/issues/155
Needs/ follows https://github.com/MarkBind/markbind/pull/156

Attempt to address the problem that live reloading crash when there are
* Multiple updates to a single file before live reloading is complete
    * Testing: Before it logs 'Page rebuilt', continue making changes to file and save repeatedly.
* Multiple files are saved at once (by the IDE)
    * Testing: Use a IDE? or make multiple changes then use Git to discard changes in multiple files after markbind serve

Attempted fix - `delay` function:
Using `rebuildSourceFiles` as an example,
 * `waitingPromise` has not started executing anything in `rebuildSourceFiles`
* `runningPromise` is still executing  `rebuildSourceFiles` and its promises and is not fulfilled/rejected yet.

Since the args are accumulated, we only need 1 `waitingPromise` (hence the `if (waitingPromise === null)` check)

Before we can do `func.apply(context, [pendingArgs])` e.g. rebuild multiple source files, we will have to
1. wait for the previous rebuild to complete (or live reloading might crash)
    * Now, `waitingPromise` must wait for `runningPromise` to be fulfilled or rejected.
2. maybe wait for some time so we can batch process a few files together
    * waitingPromise wait for `Promise.delay(wait)`
    * This isn't strictly debouncing as it ensures at least k seconds after the _first_ call is made (not the last as in debouncing)

Some examples with wait = 1 sec / further clarification
* Changes are first made to File A. We do not rebuild the file immediately. We wait for 1 second and if File B and C change within this second, they will be rebuilt together.
* If the ongoing rebuild is really slow  (e.g. 2 sec), we will just collect all the subsequent file paths that need to be rebuilt and rebuild them together after the ongoing one is complete (the 1 sec wait was already complete). This is unlike the debounce + lock approach where they will still be done in batches decided by the debounced call.
* Since the handlers in `index.js` expect to get a promise back and chain it, we return the same `waitingPromise` to all calls. If one file is missing which will cause ENOENT, multiple `catch` might be executed.

### CODE REVIEW

**Comment by acjh** [comment]
> - Every one second, rebuild all the files in the queue together and clear the queue.
>   - Use lodash's debounce

"*Every* one second" is logically different from "debounce", which is closer to "*after* one second".

> - Rebuilding the affected file might take longer than 1 second. Hence to ensure that only one rebuild per file is called, use a lock/flag.

A lock does not ensure that only one rebuild per file is called; it ensures that one is run after another.

File: index.js [hunk 1]
```diff
@@ -2,14 +2,15 @@
 
 
 // Entry file for Markbind project
+const AsyncLock = require('async-lock');
 const clear = require('clear');
 const fs = require('fs-extra-promise');
 const path = require('path');
-const Promise = require('bluebird');
```
Comment (acjh) [inline index.js]: Why remove this?

**Comment by acjh** [comment]
`debouncedBuildAssets()` calls `buildAssets()`, which calls `buildMultipleAssets(filePaths)` 😭

How about handling `debounce` in the existing `Site.prototype.buildAsset(filePath)`?
We might need https://github.com/bjoerge/debounce-promise.

File: index.js (hunk 1 above)
Comment (rachx) [reply index.js]: es-lint told me it was redundant 🙈

**Comment by rachx** [comment]
> A lock does not ensure that only one rebuild per file is called; it ensures that one is run after another.

It should be at any point in time, there is only one instance of a page rebuilding?
This is by accumulating a batch of files, getting the set of pages to rebuild, wait for all of them to be done before processing another batch. The lock was to ensure that there is no multiple batch processing at the same time.

**Comment by acjh** [comment]
> It should be at any point in time, there is only one instance of a page rebuilding?

Yes.

File: lib/Site.js [hunk 2]
```diff
@@ -74,6 +77,37 @@ function setExtension(filename, ext) {
...
+  let previousPromise = Promise.resolve();
+
+  return function (...args) {
+    context = this;
+    pendingArgs.push(args);
+
+    if (waitingPromise === null) {
+      waitingPromise = new Promise((resolve, reject) => {
+        Promise.all([Promise.delay(wait), previousPromise]).then(() => {
+          previousPromise = waitingPromise || Promise.resolve();
```
Comment (acjh) [inline lib/Site.js]: This is in a block that checks `if (waitingPromise === null)`.

---
Why don't we just return a chained Promise? Something like:

```js
return waitingPromise.then(() => func.apply(context, pendingArgs));
```

File: index.js [hunk 3]
```diff
@@ -163,7 +163,7 @@ program
       })
       .then(() => {
         const watcher = chokidar.watch(rootFolder, {
-          ignored: [outputFolder, /(^|[/\\])\../],
+          ignored: [outputFolder, /(^|[/\\])\../, '/**/*.md__jb_tmp__'],
```
Comment (rachx) [inline index.js]: @nicholaschuayunzhi Can test this? I don't get this files when I use intellij or webstorm

Comment (nicholaschuayunzhi) [reply index.js]: @rachx, I'm still getting changes recorded.
image

Also do consider ignoring html tmp files
image

Comment (nicholaschuayunzhi) [reply index.js]: this worked for me:
```js
ignored: [outputFolder, /(^|[/\\])\../, '*.md__jb_tmp__'],
```

File: lib/Site.js (hunk 2 above)
Comment (rachx) [reply lib/Site.js]: Using `rebuildSourceFiles` as an example,
 * `waitingPromise` has not started executing anything in `rebuildSourceFiles`
* `pendingPromise` is still executing  `rebuildSourceFiles` and its promises and is not fulfilled/rejected yet.

Since the args are accumulated, we only need 1 `waitingPromise` (hence the `if (waitingPromise === null)` check)

Before we can do `func.apply(context, pendingArgs)` e.g. rebuild multiple source files, we will have to
1. wait for the previous rebuild to complete (or live reloading will crash)
    * This was previously done with `async-lock`
    * Now, `waitingPromise` must wait for `pendingPromise` to be fulfilled or rejected.
2. maybe wait for some time so we can batch process a few files together
    * waitingPromise wait for `Promise.delay(wait)`
    * This isn't strictly debouncing as it ensures at least k seconds after the _first_ call is made (not the last as in debouncing)

Some examples with wait = 1 sec / further clarification
* Changes are first made to File A. We do not rebuild the file immediately. We wait for 1 second and if File B and C change within this second, they will be rebuilt together.
* If the ongoing rebuild is really slow  (e.g. 2 sec), we will just collect all the subsequent file paths that need to be rebuilt and rebuild them together after the ongoing one is complete (the 1 sec wait was already complete). This is unlike the debounce + lock approach where they will still be done in batches decided by the debounced call.
* Since the handlers in `index.js` expect to get a promise back and chain it, we return the same `waitingPromise` to all calls. If one file is missing which will cause ENOENT, multiple `catch` might be executed.

Comment (acjh) [reply lib/Site.js]: Thanks for the explanation!

I propose to remove the [explicit Promise construction](https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it):

```js
// Current
waitingPromise = new Promise((resolve, reject) => {
  Promise.all([Promise.delay(wait), previousPromise]).then(() => {
    previousPromise = waitingPromise || Promise.resolve();
    func.apply(context, pendingArgs).then(resolve, reject);
    waitingPromise = null;
    pendingArgs = [];
  });
});

// Proposed
waitingPromise = Promise.all([Promise.delay(wait), previousPromise])
  .then(() => {
    previousPromise = waitingPromise || Promise.resolve();
    waitingPromise = null;
    let funcPromise = func.apply(context, pendingArgs);
    pendingArgs = [];
    return funcPromise;
  });
```

In the "Current" case, if `previousPromise` rejects, then `waitingPromise` will never resolve (nor reject).
That said, should it be [`finally`](http://bluebirdjs.com/docs/api/finally.html) instead of `then`? Otherwise, all of the calls after a reject will always fail.

Can we also rename `previousPromise` to `runningPromise` to better reflect the running/waiting state?
Otherwise, `previousPromise = waitingPromise` looks really odd.

File: lib/Site.js [hunk 4]
```diff
@@ -74,6 +77,37 @@ function setExtension(filename, ext) {
   );
 }
 
+/**
+* Creates a function that delays invoking func until after wait milliseconds have elapsed
+* and the previous function have resolved/rejected.
```
Comment (acjh) [inline lib/Site.js]:
```diff
-* Creates a function that delays invoking func until after wait milliseconds have elapsed
-* and the previous function have resolved/rejected.
+* Creates a function that delays invoking `func` until after `wait` milliseconds have elapsed
+* and the running `func` has resolved/rejected.

File: lib/Site.js [hunk 5]
```diff
@@ -74,6 +77,37 @@ function setExtension(filename, ext) {
   );
 }
 
+/**
+* Creates a function that delays invoking `func` until after `wait` milliseconds have elapsed
+* and the running `func` have resolved/rejected.
```
Comment (acjh) [inline lib/Site.js]: "`has` resolved/rejected"

File: lib/Site.js [hunk 6]
```diff
@@ -234,37 +270,51 @@ Site.prototype.rebuildSourceFiles = function (filePath) {
   });
 };
 
-Site.prototype.buildAsset = function (filePath) {
+/**
+ * Rebuild pages that are affected by change in filePath
+ * @param filePath path corresponding to file that have changed
```
Comment (acjh) [inline lib/Site.js]: - This should use the same plural jsdoc, right?
- Can we remove the jsdoc on `_`-prefixed versions, and add to non-prefixed versions?

File: lib/Site.js [hunk 7]
```diff
@@ -234,37 +270,51 @@ Site.prototype.rebuildSourceFiles = function (filePath) {
...
+ */
+Site.prototype.rebuildSourceFiles
+  = delay(Site.prototype._rebuildSourceFiles, 1000);
+
+Site.prototype._buildMultipleAssets = function (filePaths) {
```
Comment (acjh) [inline lib/Site.js]: Can `buildAssets()` call `_buildMultipleAssets(filePaths)`?

File: lib/Site.js [hunk 8]
```diff
@@ -234,49 +266,68 @@ Site.prototype.rebuildSourceFiles = function (filePath) {
...
+ * @param filePaths paths corresponding to file that have changed
+ */
+Site.prototype.rebuildSourceFiles
+  = delay(Site.prototype._rebuildSourceFiles, 1000);
+
+Site.prototype._buildMultipleAssets = function (filePaths) {
+  const uniquePaths = _.uniq(filePaths);
+  const ignoreConfig = this.siteConfig.ignore || [];
+  const fileIgnore = ignore().add(ignoreConfig);
+  const relativeFiles = uniquePaths.map(filePath => path.relative(this.rootPath, filePath));
```
Comment (acjh) [inline lib/Site.js]: `fileRelativePaths`?

File: lib/Site.js [hunk 9]
```diff
@@ -234,49 +266,68 @@ Site.prototype.rebuildSourceFiles = function (filePath) {
...
+Site.prototype._removeMultipleAssets = function (filePaths) {
+  const uniquePaths = _.uniq(filePaths);
+  const relativeFiles = uniquePaths.map(filePath => path.relative(this.rootPath, filePath));
+  const filesToRemove = relativeFiles.map(fileRelative => path.join(this.outputPath, fileRelative));
+  const removeFiles = filesToRemove.map(asset => fs.removeAsync(asset));
   return new Promise((resolve, reject) => {
-    const fileRelative = path.relative(this.rootPath, filePath);
-    const fileToRemove = path.join(this.outputPath, fileRelative);
-    fs.removeAsync(fileToRemove)
+    Promise.all(removeFiles)
```
Comment (acjh) [inline lib/Site.js]: - Remove explicit promise construction when using `Promise.all`.
- Do the same in `Site.prototype.buildAllAssets`.

File: lib/Site.js [hunk 10]
```diff
@@ -234,49 +266,68 @@ Site.prototype.rebuildSourceFiles = function (filePath) {
...
     const outputFolder = path.relative(this.rootPath, this.outputPath);
     ignoreConfig.push(outputFolder); // ignore generated site folder
     const fileIgnore = ignore().add(ignoreConfig);
     // Scan and copy assets (excluding ignore files).
     this.listAssets(fileIgnore)
-      .then(assets =>
-        assets.map(asset => fs.copyAsync(path.join(this.rootPath, asset), path.join(this.outputPath, asset))),
-      )
-      .then(copyAssets => Promise.all(copyAssets))
+      .then(assetPaths => this._buildMultipleAssets(assetPaths))
```
Comment (acjh) [inline lib/Site.js]: Hmm, let's revert this if there's almost no benefit.

File: lib/Site.js [hunk 11]
```diff
@@ -74,6 +77,37 @@ function setExtension(filename, ext) {
   );
 }
 
+/**
+* Creates a function that delays invoking `func` until after `wait` milliseconds have elapsed
+* and the running `func` has resolved/rejected.
+* @param func the promise-returning function to delay
```
Comment (acjh) [inline lib/Site.js]: `func`'s parameter must be an array, right?

File: index.js [hunk 12]
```diff
@@ -163,7 +163,7 @@ program
       })
       .then(() => {
         const watcher = chokidar.watch(rootFolder, {
-          ignored: [outputFolder, /(^|[/\\])\../, '/**/*.md__jb_tmp__'],
+          ignored: [outputFolder, /(^|[/\\])\../, '*.md__jb_tmp__', '*.html__jb_tmp__'],
```
Comment (nicholaschuayunzhi) [inline index.js]: I'm really sorry, the previous suggestion that i mentioned didn't work - first time i tested i did not have any temp files built..
image

How about this instead:
```js
ignored: [outputFolder, /(^|[/\\])\../, path => path.endsWith('___jb_tmp___')],
```

I've tested this multiple times and had no issue. Would this be better?

**Comment by nicholaschuayunzhi** [comment]
I've found another temp file.
Reload for file deletion: D:\NUS Year 2\SEM2\markbind\website-base\book\common\definitions.md___jb_old___

File: lib/Site.js (hunk 11 above)
Comment (rachx) [reply lib/Site.js]: Nope but we can change it that way
* Currently, it is using `func.apply(context, pendingArgs);` and `pendingArgs` is supposed to be the argument list. So all the delayed functions take in a variable number of arguments `...filePaths`
* Will you prefer it to be `func.apply(context, [pendingArgs]);` instead?

File: lib/Site.js [hunk 13]
```diff
@@ -74,6 +77,37 @@ function setExtension(filename, ext) {
...
+*/
+function delay(func, wait) {
+  let context;
+  let pendingArgs = [];
+  let waitingPromise = null;
+  let runningPromise = Promise.resolve();
+
+  return function (arg) {
+    context = this;
+    pendingArgs.push(arg);
```
Comment (rachx) [inline lib/Site.js]: Also, for the non-prefixed method e.g. `rebuildSourceFiles`, 
it should only take in one `filePath` parameter.
Currently, that is how it is used in `index.js` too.

If it is supposed to be multiple parameters
then the function should take in `...args`, we should `concat` instead of `push` args or flatten the array in the delayed functions

File: lib/Site.js (hunk 11 above)
Comment (acjh) [reply lib/Site.js]: [`Function.prototype.apply()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) *calls a function with arguments provided as an array*.
The way before https://github.com/MarkBind/markbind-cli/pull/31/commits/55b874aee100d6ecbade3c4927b219ed1eb9451a is preferable, and already the case where `func`'s parameter was an array.
I meant the jsdoc should specify that.

I don't understand why `func.apply(context, [pendingArgs]);` was suggested.

File: lib/Site.js (hunk 13 above)
Comment (acjh) [reply lib/Site.js]: As I commented above: *The way before 55b874a is preferable*.
The ~spread syntax~ [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) allowed the "wrapped" function to take in one or more parameters.
We should use `concat` since the "original" function accepted an array (seems clean).

File: lib/Site.js (hunk 11 above)
Comment (rachx) [reply lib/Site.js]: Example
```js
function sum(a, b) { // does not take in an array
    return a + b;
}

function wrapsum(a, b) {
     // invalid without []
    // this passes it as sum(a,b) instead of sum([a, b])
    return sum.apply(this, [a, b]); 
}
```

If the delayed functions do not take in a variable number of arguments `...filePaths`, if there is only one path, it will call `rebuildSourceFile("filename")` which won't work as an array is expected. 

I forgot to use rest parameters for some (building assets) before 55b874a

**Comment by rachx** [comment]
@nicholaschuayunzhi @acjh updated to address all comments.
If this is okay, I will reorganise the commits

File: lib/Site.js (hunk 11 above)
Comment (acjh) [reply lib/Site.js]: That doesn't seem like a suitable example.

In our case, the wrapped function takes in a single argument — either a filename, or an array.

```js
var _pendingArgs = [];
var _sum = 0;

function sum(a) { // does not take in an array
    _sum += a;
    return _sum;
}

function wrapsum(...args) {
    _pendingArgs.push(...args);

    // Fake delay
    if (_pendingArgs < 2) return -1;
    const pendingArgs = _pendingArgs;
    _pendingArgs = [];

    return sum.apply(this, [pendingArgs]); 
}
```

I mean, if the "original" function only expects only 1 number as above, this won't work:

```js
wrapsum(1); // -1
wrapsum(2); // "01,2"
```

If its parameter is an array:

```js
var _sum = 0;

function sum(arr) { // takes in an array
    arr.forEach(a => { _sum += a });
    return _sum;
}
```
Then this will work:

```js
wrapsum(1); // -1
wrapsum(2); // 3
```

Now I understand why `func.apply(context, [pendingArgs]);` was suggested.

Comment (acjh) [reply lib/Site.js]: > Now I understand why `func.apply(context, [pendingArgs]);` was suggested.

I see that it's not necessary if *rest parameters* are used.

File: lib/Site.js [hunk 14]
```diff
@@ -234,37 +267,47 @@ Site.prototype.rebuildSourceFiles = function (filePath) {
...
-      fs.copyAsync(filePath, path.join(this.outputPath, fileRelative))
-        .then(resolve)
-        .catch((error) => {
-          rejectHandler(reject, error, []); // assets won't affect deletion
-        });
-    }
-  });
+/**
+ * Rebuild pages that are affected by change in filePath
+ * @param filePath path corresponding to file that have changed
```
Comment (acjh) [inline lib/Site.js]: Plural

File: lib/Site.js [hunk 15]
```diff
@@ -234,37 +267,47 @@ Site.prototype.rebuildSourceFiles = function (filePath) {
...
+ */
+Site.prototype.rebuildSourceFiles
+  = delay(Site.prototype._rebuildSourceFiles, 1000);
+
+Site.prototype._buildMultipleAssets = function (...filePaths) {
+  const uniquePaths = _.uniq(filePaths);
+  const ignoreConfig = this.siteConfig.ignore || [];
+  const fileIgnore = ignore().add(ignoreConfig);
+  const relativeFiles = uniquePaths.map(filePath => path.relative(this.rootPath, filePath));
```
Comment (acjh) [inline lib/Site.js]: https://github.com/MarkBind/markbind-cli/pull/31#discussion_r173386071:

> `fileRelativePaths`?

File: lib/Site.js [hunk 16]
```diff
@@ -74,6 +77,38 @@ function setExtension(filename, ext) {
   );
 }
 
+/**
+* Creates a function that delays invoking `func` until after `wait` milliseconds have elapsed
+* and the running `func` has resolved/rejected.
+* @param func the promise-returning function to delay,
+*        func should be able to take in an indefinite amount of arguments
```
Comment (acjh) [inline lib/Site.js]: Continuing from https://github.com/MarkBind/markbind-cli/pull/31#discussion_r173388278:

> aaron:
> `func`'s parameter must be an array, right?

> rachx:
> Nope but we can change it that way
> * Currently, it is using `func.apply(context, pendingArgs);` and `pendingArgs` is supposed to be the argument list. So all the delayed functions take in a variable number of arguments `...filePaths`
> * Will you prefer it to be `func.apply(context, [pendingArgs]);` instead?

1. Can we require that the original  `func` take in an array, and limit `arg` of the wrapped function to a single parameter? This doesn't seem like a good use case for *spread syntax* and *rest parameters*. For flexibility, we can add a check for whether `arg` is already an array or a single value.
2. Let's rename `rebuildSourceFiles` to `rebuildAffectedSourceFiles` to better reflect what it does (similar to the existing `regenerateAffectedPages`).

Comment (rachx) [reply lib/Site.js]: To clarify,

> Can we require that the original func take in an array

Does this mean removing the rest parameters in `rebuildSourceFiles` etc and ensuring an array is always passed in, e.g. by using `[pendingArgs]` and updating the jsdocs accordingly?

>limit arg of the wrapped function to a single parameter

Does this mean changing `function (...args)` [[code](https://github.com/MarkBind/markbind-cli/pull/31/files#diff-e5f3ecb7effaa21db6153e4647ea22bcR93)] in `delay` to  `function (arg)`. 

So `arg` in `rebuildSourceFiles` (the non-prefixed method) can be a single value or array

> This doesn't seem like a good use case for spread syntax and rest parameters.

Which lines are you referring to?
1. `return function (...args)` 
2.  `pendingArgs.push(...args);` to extend an array
3. `Site.prototype._buildMultipleAssets = function (...filePaths)`

Comment (acjh) [reply lib/Site.js]: > Does this mean removing the rest parameters in `rebuildSourceFiles` etc and ensuring an array is always passed in, e.g. by using `[pendingArgs]` and updating the jsdocs accordingly?

Yes.

> Does this mean changing `function (...args)` [[code](https://github.com/MarkBind/markbind-cli/pull/31/files#diff-e5f3ecb7effaa21db6153e4647ea22bcR93)] in `delay` to  `function (arg)`. 
>
> So `arg` in `rebuildSourceFiles` (the non-prefixed method) can be a single value or array

Yes.

> Which lines are you referring to?

*This* as in our use case of passing in a single `filePath` for "original" function accepting an array.
1. is not useful because we really won't be calling it as `buildAsset(filePath1, filePath2)` even if we have multiple files. It makes more sense to pass in an array.
2. seems reasonable at first, but flattening defeats the purpose of rest parameters.
  e.g. If we have an "original" function that accepts (`param1`, `param2`), `pendingArgs` becomes `[param1_first, param2_first, param1_second, param2_second]`. So we're already expecting the "original" function to collect it into an array via rest parameters.
3. is not useful for the same reason as 1.

**Comment by rachx** [comment]
Force pushed

**Comment by nicholaschuayunzhi** [comment]
I've tested abit and it works well with md files especially if its only content. The delay works well to queue up all other actions.

However when i delete files, i think the rebuild process does not work (or it takes too long due to all the logging) and when i readd the files, not all the files are rebuilt. I think this can be handled in a different PR.

**Comment by rachx** [comment]
> However when i delete files, i think the rebuild process does not work (or it takes too long due to all the logging) and when i read the files, not all the files are rebuilt. I think this can be handled in a different PR.

Can you elaborate?

I have tested deleting files before - the page that includes those files did rebuild, fresh and show an error that the referenced page was missing.

However, the error was logged in the console multiple times

Also when I tested in the past, sometimes it seems to "hang" and will work when I type enter or something in the command line

**Comment by nicholaschuayunzhi** [comment]
When i delete `book/common/definitions.md`, its logs alot of missing files and I'm not sure when the rebuilding process will complete.

**Comment by rachx** [comment]
It might not be related to PR.

`book/common/definitions.md` should be one of the page model.
It also affects over 100 of other pages.
When `readFile` fails in markbind `includeFile` function, it rejects, triggering a chain of reject handlers including `removeAsync` to remove the temp and site folder.
This can be interleaved between the (wasteful) rebuilding of the 100 of pages (which are trying to write to the temp and site folder) and might be the cause of permission errors:
```
ERROR: { Error: EPERM: operation not permitted, lstat 'C:\Users\rachael\Desktop\\MarkBind\website\_site\book\javaTools'
errno: -4048,
code: 'EPERM',
syscall: 'lstat',
path: 'C:\\Users\\rachael\Desktop\\MarkBind\\website\\_site\\book\\javaTools' }
```
I got multiple of these.

**Comment by rachx** [comment]
@acjh

File: lib/Site.js [hunk 17]
```diff
@@ -283,37 +321,48 @@ Site.prototype.rebuildSourceFiles = function (filePath) {
...
+  const filesToRemove = fileRelativePaths.map(
+    fileRelativePath => path.join(this.outputPath, fileRelativePath));
+  const removeFiles = filesToRemove.map(asset => fs.removeAsync(asset));
+  return Promise.all(removeFiles)
+    .then(() => logger.info('Assets removed'));
 };
 
+/**
+ * Remove assets that are specified in filePaths
+ * @param filePaths a single path or an array of patsh corresponding to the assets to remove
```
Comment (acjh) [inline lib/Site.js]: Typo: ~`patsh`~`paths`

**Review by acjh — APPROVED** [review]
Good work!

File: lib/Site.js [hunk 18]
```diff
@@ -81,6 +84,43 @@ function setExtension(filename, ext) {
...
 
+/**
+* Creates a function that delays invoking `func` until after `wait` milliseconds have elapsed
+* and the running `func` has resolved/rejected.
+* @param func the promise-returning function to delay,
+*        func should take in a single array
+* @param wait the number of milliseconds to delay
+* @returns delayedFunc that takes in a single argument (either an array or a single value)
+*/
+function delay(func, wait) {
```
Comment (Gisonrg) [inline lib/Site.js]: nit: this function should live under a utility file in `./util/` since it could be used in other places than `Site.js`.

**Review by Gisonrg — APPROVED** [review]

**Comment by acjh** [comment]
@rachx You can merge this :)
